### ISSUE TITLE
Supporters logo grid should include urls

### ISSUE THREAD

**Issue by maneesha** [carpentries/tnd-carpentries-working#84]
The [supporters logo grid](https://github.com/carpentries/tnd-carpentries-working/blob/main/themes/carpentries/layouts/partials/blocks/templates/logo-grid.html) takes a list of images passed in from the front page yaml data.  This should instead take images and URLs so clicking on the image will take the user to that website.

**Comment by AdamChlan** [comment]
@maneesha here is an example how you can add URLs to the image:

```
  logos:
  - logo: moore-logo.svg
    url: https://www.apple.com
  - logo: alfred-sloan-logo.svg
  - logo: chan-zuck-logo.svg
  - logo: r-studio-logo.svg
  ```
